version: '2'
services:
 mysql:
  build: mysql
  expose:
  - "3306"
  ports:
  - "3306:3306"
  env_file:
  - ./env_vars
 mdl:
  build: mdl
  ports:
   - "8080:80"
  depends_on:
   - nfs
   - mysql
  env_file:
   - ./env_vars
 nfs:
  build: nfs
  ports:
  - "111:111"
  - "2049:2049"
 redis:
  image: redis
  expose:
  - "6379"
  ports:
  - "6379:6379"
  env_file:
    - ./env_vars
