version: '2'
services:

 mdl:
  build: mdl
  ports:
   - "81:80"
  depends_on:
   - nfs
   - mysql
  environment:
    MDL_USERNAME: padmin
    MDL_PASSWORD: password
    MDL_HOSTNAME: www.pulse.pearson.com

 nfs:
  build: nfs
  ports:
  - "111:111"
  - "2049:2049"

 mysql:
  image: mysql:latest
  expose:
  - "3306"
  ports:
  - "3307:3306"
  environment:
   MYSQL_ROOT_PASSWORD: Pearson
   MYSQL_DATABASE: moodle
   MYSQL_USER: moodle
   MYSQL_PASSWORD: Pearson
