version: '2'
services:
 mysql:
  image: mysql:latest
  expose:
  - "3306"
  ports:
  - "3306:3306"
  env_file:
    - ./env_vars
 mdl:
  build: mdl
  ports:
   - "80"
  depends_on:
   - nfs
   - mysql
  links:
   - mysql
  env_file:
   - ./env_vars
 nfs:
  build: nfs
  ports:
  - "111:111"
  - "2049:2049"
